<template>
  <section class="debug-panel" :class="{ collapsed }">
    <header><div><strong>Fesod 数据模拟</strong><span>Mock JSON 与单元格映射</span></div><div><button @click="$emit('run')">▶ 运行</button><button @click="$emit('export')">⇩ 导出</button><button @click="$emit('toggle')">{{ collapsed ? '展开' : pinned ? '取消 Pin' : 'Pin' }}</button></div></header>
    <div v-show="!collapsed" class="debug-content"><textarea class="json-editor" :value="modelValue" spellcheck="false" @input="$emit('update:modelValue', ($event.target as HTMLTextAreaElement).value)"></textarea><div class="mapping-panel"><div class="mapping-head"><strong>变量绑定</strong><button @click="addMapping">＋</button></div><p v-if="!mappings.length">选择一个单元格后，添加 JSONPath 映射。</p><label v-for="(mapping,index) in mappings" :key="index"><span>{{ mapping.cellAddress || '未选择单元格' }}</span><input v-model="mapping.jsonPath" placeholder="$.customer.name" /><button @click="mappings.splice(index,1)">×</button></label><small>{{ status }}</small></div></div>
  </section>
</template>
<script setup lang="ts">
import type { Mapping } from '../stores/workshop'
const props = defineProps<{ modelValue: string; mappings: Mapping[]; selectedCell?: { sheetId: string; cellAddress: string }; collapsed: boolean; pinned: boolean; status: string }>()
defineEmits(['update:modelValue', 'run', 'export', 'toggle'])
function addMapping() { props.mappings.push({ sheetId: props.selectedCell?.sheetId || 'sheet-1', cellAddress: props.selectedCell?.cellAddress || '', jsonPath: '' }) }
</script>
<style scoped>.debug-panel{min-height:210px;border-top:1px solid var(--border);background:var(--surface-raised);display:grid;grid-template-rows:auto 1fr}.debug-panel.collapsed{min-height:38px;grid-template-rows:auto}.debug-panel header{display:flex;justify-content:space-between;align-items:center;padding:7px 10px;border-bottom:1px solid var(--border);font:12px var(--font)}header span{color:var(--muted);margin-left:10px}button{border:1px solid var(--border);border-radius:3px;background:var(--button);color:var(--text);padding:4px 8px;margin-left:4px;cursor:pointer;font:inherit}.debug-content{display:grid;grid-template-columns:1.35fr 1fr;min-height:0}.json-editor{min-height:170px;border:0;border-right:1px solid var(--border);resize:none;background:var(--input);color:var(--text);padding:10px;font:12px var(--font);outline:none}.mapping-panel{padding:9px;overflow:auto;font:12px var(--font)}.mapping-head{display:flex;justify-content:space-between}.mapping-panel p,.mapping-panel small{color:var(--muted)}.mapping-panel label{display:grid;grid-template-columns:80px 1fr auto;gap:5px;align-items:center;margin:7px 0}.mapping-panel input{min-width:0;border:1px solid var(--border);background:var(--input);color:var(--text);padding:4px}</style>
