const encoder = new TextEncoder()

function crc32(data: Uint8Array) { let crc = -1; for (const byte of data) { crc ^= byte; for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1)) } return (crc ^ -1) >>> 0 }
function write16(target: number[], value: number) { target.push(value & 0xff, (value >>> 8) & 0xff) }
function write32(target: number[], value: number) { target.push(value & 0xff, (value >>> 8) & 0xff, (value >>> 16) & 0xff, (value >>> 24) & 0xff) }
function escapeXml(value: unknown) { return String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }
function column(index: number) { let name = ''; let value = index + 1; while (value) { const rest = (value - 1) % 26; name = String.fromCharCode(65 + rest) + name; value = Math.floor((value - 1) / 26) } return name }
function zip(entries: Array<[string, string]>) {
  const output: number[] = []; const central: number[] = []; let offset = 0
  for (const [name, text] of entries) { const nameBytes = encoder.encode(name); const data = encoder.encode(text); const checksum = crc32(data); write32(output, 0x04034b50); write16(output, 20); write16(output, 0); write16(output, 0); write16(output, 0); write16(output, 0); write32(output, checksum); write32(output, data.length); write32(output, data.length); write16(output, nameBytes.length); write16(output, 0); output.push(...nameBytes, ...data); write32(central, 0x02014b50); write16(central, 20); write16(central, 20); write16(central, 0); write16(central, 0); write16(central, 0); write16(central, 0); write32(central, checksum); write32(central, data.length); write32(central, data.length); write16(central, nameBytes.length); write16(central, 0); write16(central, 0); write16(central, 0); write16(central, 0); write32(central, 0); write32(central, offset); central.push(...nameBytes); offset = output.length }
  const centralOffset = output.length; output.push(...central); write32(output, 0x06054b50); write16(output, 0); write16(output, 0); write16(output, entries.length); write16(output, entries.length); write32(output, central.length); write32(output, centralOffset); write16(output, 0); return new Uint8Array(output).buffer
}
function sheetXml(snapshot: any) { const sheet = snapshot?.sheets?.['sheet-1'] || {}; const rows: string[] = []; for (const [rowIndex, cells] of Object.entries(sheet.cellData || {})) { const content = Object.entries(cells as Record<string, any>).map(([columnIndex, cell]) => { const ref = `${column(Number(columnIndex))}${Number(rowIndex) + 1}`; return cell?.f ? `<c r="${ref}"><f>${escapeXml(String(cell.f).replace(/^=/, ''))}</f></c>` : `<c r="${ref}" t="inlineStr"><is><t>${escapeXml(cell?.v)}</t></is></c>` }).join(''); rows.push(`<row r="${Number(rowIndex) + 1}">${content}</row>`) } return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.join('')}</sheetData></worksheet>` }
self.onmessage = (event: MessageEvent<{ snapshot: any }>) => { try { const snapshot = event.data.snapshot; const name = escapeXml(snapshot?.sheets?.['sheet-1']?.name || 'Sheet1'); const buffer = zip([['[Content_Types].xml', '<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'], ['_rels/.rels', '<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'], ['xl/workbook.xml', `<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${name}" sheetId="1" r:id="rId1"/></sheets></workbook>`], ['xl/_rels/workbook.xml.rels', '<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships></Relationships>'], ['xl/worksheets/sheet1.xml', sheetXml(snapshot)]]); (self as any).postMessage({ ok: true, buffer }, [buffer]) } catch (error) { (self as any).postMessage({ ok: false, error: error instanceof Error ? error.message : '导出失败' }) } }
