<template>
  <section class="console-page">
    <div class="page-header"><div><h2>配置管理</h2><p>按命名空间维护配置项，并支持配置键投影与持久化目录。</p></div><div class="page-header-meta">当前 {{ namespaces.length }} 个命名空间 / {{ items.length }} 个配置项</div></div>
    <el-card shadow="never" class="toolbar-card"><div class="toolbar-grid"><div class="toolbar-title">筛选条件</div><el-select v-model="selectedNamespaceId" placeholder="请选择命名空间" @change="handleNamespaceChange"><el-option v-for="namespace in namespaces" :key="namespace.id" :label="namespaceLabel(namespace)" :value="namespace.id" /></el-select><el-input v-model.trim="keyword" placeholder="配置键或配置值" clearable @keyup.enter="loadItems" /><div class="toolbar-actions"><el-button @click="resetFilters">重置</el-button><el-button type="primary" :loading="itemsLoading" @click="loadItems">查询</el-button><el-button @click="namespaceManagerVisible = true">管理命名空间</el-button><el-button type="success" :disabled="!selectedNamespace" @click="openItemCreate">新建配置项</el-button></div></div></el-card>
    <el-card shadow="never" class="table-card"><div class="config-workspace"><aside class="tree-panel"><div class="tree-panel-header"><div><span>配置目录</span><el-tag v-if="selectedNamespace" size="small" effect="plain">{{ selectedNamespace.directoryMode === 'DIRECTORY_API' ? '目录接口' : '键投影' }}</el-tag></div><div><el-button v-if="isDirectoryMode" link type="primary" @click="openDirectoryCreate()">新建目录</el-button><el-button link type="primary" @click="clearTreeSelection">全部</el-button></div></div><p v-if="selectedNamespace && !isDirectoryMode" class="tree-hint">目录由配置键中的冒号自动生成。</p><el-tree ref="treeRef" :key="treeVersion" :data="treeData" node-key="nodeKey" :props="treeProps" :default-expanded-keys="expandedKeys" :expand-on-click-node="false" highlight-current @node-click="handleTreeNodeClick"><template #default="{ data }"><span class="tree-node"><span>{{ data.label }}</span><span v-if="data.kind === 'directory'" class="tree-node-actions"><el-button v-if="isDirectoryMode && data.kind !== 'root'" link type="primary" @click.stop="openDirectoryEdit(data)">编辑</el-button><el-button v-if="isDirectoryMode && data.kind !== 'root'" link type="danger" @click.stop="confirmDirectoryDelete(data)">删除</el-button><small>{{ data.itemCount ?? data.itemIds?.length ?? 0 }}</small></span></span></template></el-tree></aside><div class="items-panel"><div class="items-panel-title">{{ activeTreeLabel || '全部配置项' }}</div><el-table :data="visibleItems" v-loading="itemsLoading"><el-table-column prop="itemKey" label="配置键" min-width="210" class-name="code-cell" /><el-table-column label="配置值" min-width="220"><template #default="{ row }"><el-tooltip :content="row.itemValue"><span class="value-preview">{{ row.itemValue }}</span></el-tooltip></template></el-table-column><el-table-column prop="valueType" label="值类型" width="110"><template #default="{ row }"><el-tag effect="plain">{{ row.valueType }}</el-tag></template></el-table-column><el-table-column prop="env" label="环境" width="90" /><el-table-column label="操作" width="150" fixed="right"><template #default="{ row }"><div class="row-actions"><el-button link type="primary" @click="openItemEdit(row)">编辑</el-button><el-button link type="danger" @click="confirmItemDelete(row)">删除</el-button></div></template></el-table-column></el-table></div></div></el-card>

    <el-drawer v-model="itemEditorVisible" :title="itemEditorMode === 'create' ? '新建配置项' : '编辑配置项'" size="560px" destroy-on-close><el-form ref="itemFormRef" :model="itemForm" :rules="itemRules" label-position="top"><el-form-item label="所属命名空间" prop="namespaceId"><el-select v-model="itemForm.namespaceId" :disabled="itemEditorMode === 'edit'" @change="syncItemDirectory"><el-option v-for="namespace in namespaces" :key="namespace.id" :label="namespaceLabel(namespace)" :value="namespace.id" /></el-select></el-form-item><el-form-item v-if="itemNamespace?.directoryMode === 'DIRECTORY_API'" label="所属目录"><el-tree-select v-model="itemForm.directoryId" :data="directorySelectTree" node-key="id" :props="{ label: 'name', children: 'children' }" check-strictly clearable placeholder="根目录（未归类）" /></el-form-item><el-form-item label="配置键" prop="itemKey"><el-input v-model.trim="itemForm.itemKey" placeholder="例如 token:user:1" /></el-form-item><el-form-item label="值类型" prop="valueType"><el-select v-model="itemForm.valueType" @change="validateValue"><el-option label="字符串" value="STRING" /><el-option label="整数" value="INTEGER" /><el-option label="布尔值" value="BOOLEAN" /><el-option label="JSON" value="JSON" /></el-select></el-form-item><el-form-item label="配置值" prop="itemValue"><JsonValueEditor v-if="itemForm.valueType === 'JSON'" v-model="itemForm.itemValue" @validation-change="jsonValid = $event" /><el-select v-else-if="itemForm.valueType === 'BOOLEAN'" v-model="itemForm.itemValue"><el-option label="true" value="true" /><el-option label="false" value="false" /></el-select><el-input v-else v-model="itemForm.itemValue" :inputmode="itemForm.valueType === 'INTEGER' ? 'numeric' : undefined" type="textarea" :rows="itemForm.valueType === 'STRING' ? 5 : 2" /></el-form-item><el-alert v-if="valueError" type="error" :closable="false" :title="valueError" /><el-form-item label="描述"><el-input v-model.trim="itemForm.description" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><div class="drawer-footer"><el-button @click="itemEditorVisible = false">取消</el-button><el-button type="primary" :loading="itemSaving" @click="submitItem">保存</el-button></div></template></el-drawer>

    <el-drawer v-model="namespaceManagerVisible" title="命名空间管理" size="760px" destroy-on-close><div class="namespace-toolbar"><el-button type="success" @click="openNamespaceCreate">新建命名空间</el-button></div><el-table :data="namespaces"><el-table-column prop="namespaceCode" label="命名空间" /><el-table-column prop="env" label="环境" width="100" /><el-table-column prop="directoryMode" label="目录模式" width="130" /><el-table-column prop="itemCount" label="配置项数" width="100" /><el-table-column label="操作" width="150"><template #default="{ row }"><el-button link type="primary" @click="openNamespaceEdit(row)">编辑</el-button><el-button link type="danger" @click="confirmNamespaceDelete(row)">删除</el-button></template></el-table-column></el-table></el-drawer>
    <el-dialog v-model="namespaceEditorVisible" :title="namespaceEditorMode === 'create' ? '新建命名空间' : '编辑命名空间'" width="480px"><el-form ref="namespaceFormRef" :model="namespaceForm" :rules="namespaceRules" label-position="top"><el-form-item label="命名空间编码" prop="namespaceCode"><el-input v-model.trim="namespaceForm.namespaceCode" /></el-form-item><el-form-item label="环境" prop="env"><el-input v-model.trim="namespaceForm.env" /></el-form-item><el-form-item label="展示名称" prop="displayName"><el-input v-model.trim="namespaceForm.displayName" /></el-form-item><el-form-item label="目录模式" prop="directoryMode"><el-radio-group v-model="namespaceForm.directoryMode"><el-radio-button label="KEY_PROJECTION">配置键投影</el-radio-button><el-radio-button label="DIRECTORY_API">目录接口</el-radio-button></el-radio-group></el-form-item><el-form-item label="描述"><el-input v-model.trim="namespaceForm.description" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><div class="drawer-footer"><el-button @click="namespaceEditorVisible = false">取消</el-button><el-button type="primary" :loading="namespaceSaving" @click="submitNamespace">保存</el-button></div></template></el-dialog>
    <el-dialog v-model="directoryEditorVisible" :title="directoryForm.id ? '编辑目录' : '新建目录'" width="460px"><el-form ref="directoryFormRef" :model="directoryForm" :rules="directoryRules" label-position="top"><el-form-item label="目录名称" prop="name"><el-input v-model.trim="directoryForm.name" /></el-form-item><el-form-item label="父目录"><el-tree-select v-model="directoryForm.parentId" :data="directorySelectTree" node-key="id" :props="{ label: 'name', children: 'children' }" check-strictly clearable placeholder="根目录" /></el-form-item><el-form-item label="描述"><el-input v-model.trim="directoryForm.description" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><div class="drawer-footer"><el-button @click="directoryEditorVisible = false">取消</el-button><el-button type="primary" :loading="directorySaving" @click="submitDirectory">保存</el-button></div></template></el-dialog>
  </section>
</template>
<script setup>
import { computed, nextTick, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import JsonValueEditor from '../components/JsonValueEditor.vue'
import { deleteDirectory, deleteItem, deleteNamespace, fetchDirectoryTree, fetchItemDetail, fetchItems, fetchNamespaces, saveDirectory, saveItem, saveNamespace, updateDirectory } from '../api/configAdminApi'
const namespaces=ref([]), items=ref([]), directoryTree=ref([]), selectedNamespaceId=ref(), keyword=ref(''), selectedNode=ref(), expandedKeys=ref([]), treeVersion=ref(0), itemsLoading=ref(false), itemSaving=ref(false), namespaceSaving=ref(false), directorySaving=ref(false), itemEditorVisible=ref(false), namespaceManagerVisible=ref(false), namespaceEditorVisible=ref(false), directoryEditorVisible=ref(false), itemEditorMode=ref('create'), jsonValid=ref(true), valueError=ref('')
const itemFormRef=ref(), namespaceFormRef=ref(), directoryFormRef=ref(), treeRef=ref()
const itemForm=reactive(newItem()), namespaceForm=reactive(newNamespace()), directoryForm=reactive(newDirectory())
const treeProps={label:'label',children:'children'}
const itemRules={namespaceId:[{required:true,message:'请选择命名空间',trigger:'change'}],itemKey:[{validator:(_r,v,c)=>/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}(?::[A-Za-z0-9][A-Za-z0-9._-]{0,63})*$/.test(v||'')?c():c(new Error('配置键格式无效')),trigger:'blur'}],valueType:[{required:true,message:'请选择值类型',trigger:'change'}],itemValue:[{required:true,message:'请输入配置值',trigger:'blur'}]}
const namespaceRules={namespaceCode:[{required:true,message:'请输入命名空间编码',trigger:'blur'}],env:[{required:true,message:'请输入环境',trigger:'blur'}],displayName:[{required:true,message:'请输入展示名称',trigger:'blur'}]}
const directoryRules={name:[{required:true,message:'请输入目录名称',trigger:'blur'}]}
const selectedNamespace=computed(()=>namespaces.value.find(n=>n.id===selectedNamespaceId.value)); const itemNamespace=computed(()=>namespaces.value.find(n=>n.id===itemForm.namespaceId)); const isDirectoryMode=computed(()=>selectedNamespace.value?.directoryMode==='DIRECTORY_API'); const activeTreeLabel=computed(()=>selectedNode.value?.label||''); const treeData=computed(()=>isDirectoryMode.value?[{id:null,nodeKey:'root',label:'未归类配置项',kind:'root',children:[]},...mapDirectoryTree(directoryTree.value)]:buildKeyTree(items.value)); const directorySelectTree=computed(()=>directoryTree.value)
const visibleItems=computed(()=>{if(isDirectoryMode.value||!selectedNode.value)return items.value;const ids=new Set(selectedNode.value.itemIds||[]);return items.value.filter(item=>ids.has(item.id))})
watch(treeData, tree=>{if(!selectedNode.value) expandedKeys.value=tree.map(n=>n.nodeKey)})
onMounted(async()=>{await loadNamespaces(); if(namespaces.value.length){selectedNamespaceId.value=namespaces.value[0].id;await handleNamespaceChange()}})
async function loadNamespaces(){try{namespaces.value=await fetchNamespaces()}catch(e){ElMessage.error(e.message||'加载命名空间失败')}}
async function handleNamespaceChange(){clearTreeSelection(); directoryTree.value=[]; if(isDirectoryMode.value) await loadDirectoryTree(); await loadItems()}
async function loadDirectoryTree(){if(!selectedNamespaceId.value)return;try{directoryTree.value=await fetchDirectoryTree(selectedNamespaceId.value)}catch(e){ElMessage.error(e.message||'加载目录树失败')}}
async function loadItems(){if(!selectedNamespaceId.value){items.value=[];return}itemsLoading.value=true;try{const directoryId=isDirectoryMode.value&&selectedNode.value?.kind!=='root'?selectedNode.value?.id:undefined;items.value=await fetchItems(selectedNamespaceId.value,keyword.value,directoryId);if(isDirectoryMode.value&&selectedNode.value?.kind==='root')items.value=items.value.filter(item=>item.directoryId==null);treeVersion.value++}catch(e){ElMessage.error(e.message||'加载配置项失败')}finally{itemsLoading.value=false}}
function resetFilters(){keyword.value='';clearTreeSelection();loadItems()} function clearTreeSelection(){selectedNode.value=undefined;treeRef.value?.setCurrentKey(undefined)} function namespaceLabel(n){return `${n.displayName} (${n.namespaceCode} / ${n.env})`}
function handleTreeNodeClick(node){selectedNode.value=node;loadItems()}
async function openItemCreate(){Object.assign(itemForm,newItem({namespaceId:selectedNamespaceId.value,directoryId:isDirectoryMode.value?selectedNode.value?.id:null}));itemEditorMode.value='create';valueError.value='';jsonValid.value=true;itemEditorVisible.value=true;await nextTick();itemFormRef.value?.clearValidate()}
async function openItemEdit(row){try{Object.assign(itemForm,newItem(await fetchItemDetail(row.id)));itemEditorMode.value='edit';valueError.value='';jsonValid.value=true;itemEditorVisible.value=true;await nextTick();itemFormRef.value?.clearValidate()}catch(e){ElMessage.error(e.message||'加载配置项失败')}}
function validateValue(){const v=itemForm.itemValue;if(itemForm.valueType==='INTEGER')valueError.value=/^-?(0|[1-9]\d*)$/.test(v||'')?'' :'INTEGER 必须是严格的 64 位十进制整数';else if(itemForm.valueType==='BOOLEAN')valueError.value=v==='true'||v==='false'?'':'BOOLEAN 只能是 true 或 false';else if(itemForm.valueType==='JSON')valueError.value=jsonValid.value?'':'JSON 必须是对象或数组';else valueError.value=''}
async function submitItem(){try{validateValue();await itemFormRef.value?.validate();if(itemForm.valueType==='JSON'&&!jsonValid.value){valueError.value='JSON 必须是对象或数组';return}if(valueError.value)return;itemSaving.value=true;await saveItem({...itemForm});itemEditorVisible.value=false;ElMessage.success('配置项已保存');await loadNamespaces();await handleNamespaceChange()}catch(e){if(e?.message)ElMessage.error(e.message)}finally{itemSaving.value=false}}
async function confirmItemDelete(row){try{await ElMessageBox.confirm(`确定删除配置项“${row.itemKey}”吗？`,'删除配置项',{type:'warning'});await deleteItem(row.id);ElMessage.success('配置项已删除');await loadItems()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message||'删除失败')}}
function openNamespaceCreate(){Object.assign(namespaceForm,newNamespace());namespaceEditorVisible.value=true}function openNamespaceEdit(row){Object.assign(namespaceForm,newNamespace(row));namespaceEditorVisible.value=true}
async function submitNamespace(){try{await namespaceFormRef.value?.validate();namespaceSaving.value=true;await saveNamespace({...namespaceForm});namespaceEditorVisible.value=false;await loadNamespaces();if(selectedNamespaceId.value===namespaceForm.id)await handleNamespaceChange();ElMessage.success('命名空间已保存')}catch(e){if(e?.message)ElMessage.error(e.message)}finally{namespaceSaving.value=false}}
async function confirmNamespaceDelete(row){try{await ElMessageBox.confirm(`确定删除命名空间“${namespaceLabel(row)}”吗？`,'删除命名空间',{type:'warning'});await deleteNamespace(row.id);if(selectedNamespaceId.value===row.id)selectedNamespaceId.value=undefined;await loadNamespaces();await handleNamespaceChange()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message||'删除失败')}}
function openDirectoryCreate(parent){Object.assign(directoryForm,newDirectory({namespaceId:selectedNamespaceId.value,parentId:parent?.id??selectedNode.value?.id??null}));directoryEditorVisible.value=true}function openDirectoryEdit(row){Object.assign(directoryForm,newDirectory({id:row.id,namespaceId:selectedNamespaceId.value,parentId:row.parentId,name:row.name,description:row.description}));directoryEditorVisible.value=true}
async function submitDirectory(){try{await directoryFormRef.value?.validate();directorySaving.value=true;if(directoryForm.id)await updateDirectory(directoryForm.id,{...directoryForm});else await saveDirectory({...directoryForm});directoryEditorVisible.value=false;await loadDirectoryTree();treeVersion.value++;ElMessage.success('目录已保存')}catch(e){if(e?.message)ElMessage.error(e.message)}finally{directorySaving.value=false}}
async function confirmDirectoryDelete(row){try{await ElMessageBox.confirm(`确定删除目录“${row.name}”吗？`,'删除目录',{type:'warning'});await deleteDirectory(row.id);await loadDirectoryTree();treeVersion.value++;ElMessage.success('目录已删除')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message||'删除失败')}}
function syncItemDirectory(){itemForm.directoryId=null}function mapDirectoryTree(nodes){return nodes.map(n=>({ ...n,nodeKey:`directory:${n.id}`,label:n.name,kind:'directory',children:mapDirectoryTree(n.children||[]) }))}function buildKeyTree(source){const roots=[],dirs=new Map();for(const item of source){let children=roots,path='';for(const [i,part] of item.itemKey.split(':').entries()){path=path?`${path}:${part}`:part;if(i===item.itemKey.split(':').length-1){children.push({nodeKey:`item:${item.id}`,label:part,kind:'item',id:item.id,children:[]});continue}let d=dirs.get(path);if(!d){d={nodeKey:`directory:${path}`,label:part,kind:'directory',itemIds:[],children:[]};dirs.set(path,d);children.push(d)}d.itemIds.push(item.id);children=d.children}}return roots}function newItem(s={}){return{id:s.id??null,namespaceId:s.namespaceId??'',directoryId:s.directoryId??null,itemKey:s.itemKey??'',itemValue:s.itemValue??'',valueType:s.valueType??'STRING',description:s.description??''}}function newNamespace(s={}){return{id:s.id??null,namespaceCode:s.namespaceCode??'',env:s.env??'',displayName:s.displayName??'',description:s.description??'',directoryMode:s.directoryMode??'KEY_PROJECTION'}}function newDirectory(s={}){return{id:s.id??null,namespaceId:s.namespaceId??null,parentId:s.parentId??null,name:s.name??'',description:s.description??'',sortOrder:0}}
</script>
<style scoped>
.console-page{display:grid;gap:12px}.page-header{display:flex;justify-content:space-between;gap:16px}.page-header h2{margin:0;color:var(--shell-tool-header-text)}.page-header p{margin:6px 0 0;color:var(--shell-text-secondary);font-size:13px}.page-header-meta{padding:7px 12px;border:1px solid var(--shell-tool-border-strong);border-radius:6px;background:var(--shell-tool-surface-muted);font-size:12px}.toolbar-card,.table-card{border:1px solid var(--shell-tool-border-strong);border-radius:8px;background:var(--shell-tool-surface);box-shadow:none}.toolbar-grid{display:grid;grid-template-columns:auto minmax(200px,1fr) minmax(220px,1fr) auto;gap:8px;align-items:center}.toolbar-title,.tree-hint{color:var(--shell-tool-subtle-text);font-size:12px}.toolbar-actions,.row-actions,.drawer-footer,.tree-panel-header{display:flex;align-items:center;gap:6px;justify-content:flex-end}.config-workspace{display:grid;grid-template-columns:280px minmax(0,1fr);min-height:480px}.tree-panel{padding-right:12px;border-right:1px solid var(--shell-tool-divider)}.tree-panel-header{justify-content:space-between;min-height:36px}.tree-node{display:flex;width:100%;justify-content:space-between;gap:8px}.tree-node-actions{display:flex;gap:3px;align-items:center}.tree-node small{color:var(--shell-text-muted)}.items-panel{padding-left:12px;min-width:0}.items-panel-title{height:36px;color:var(--shell-tool-subtle-text);font-size:12px;font-weight:600}.value-preview{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.namespace-toolbar{display:flex;justify-content:flex-end;margin-bottom:12px}.table-card :deep(.el-card__body),.toolbar-card :deep(.el-card__body){padding:10px 12px;background:var(--shell-tool-surface)}.items-panel :deep(.el-table){--el-table-border-color:var(--shell-tool-divider);--el-table-header-bg-color:var(--shell-tool-toolbar-bg);--el-table-row-hover-bg-color:var(--shell-tool-hover);font-size:12px}.items-panel :deep(.code-cell .cell){font-family:Consolas,monospace}.tree-panel :deep(.el-tree){background:transparent;color:var(--shell-text-primary);font-size:12px}@media(max-width:900px){.config-workspace{grid-template-columns:1fr}.tree-panel{border-right:0;border-bottom:1px solid var(--shell-tool-divider);padding-bottom:12px}.items-panel{padding:12px 0 0}}@media(max-width:720px){.toolbar-grid{grid-template-columns:1fr}.toolbar-title,.toolbar-actions{grid-column:1/-1;justify-content:flex-start}}
</style>
